include:
  - services/gluetun.yml
  - services/qbittorrent.yml
  - services/sonarr.yml
  - services/radarr.yml
  - services/prowlarr.yml
  - services/flaresolverr.yml
  - services/jellyseerr.yml
  - services/jellyfin.yml
  - services/homepage.yml
  - services/sabnzbd.yml
  - services/ntfy.yml
  - services/pipeline-status.yml

networks:
  movieseer:
    driver: bridge
