line-length = 99
target-version = "py312"
fix = true

[lint]
select = ["E", "F", "I", "B", "UP", "N", "S", "TCH"]
ignore=["TC001", "TC003"]
exclude = [
    "tests/*", 
    "scripts/*", 
    "docs/*", 
    "vpn_configurations/*", 
    "services/*"
]
