services:
  jellyseerr:
    image: fallenbagel/jellyseerr
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - "${JELLYSEERR_PORT}:5055"
    volumes:
      - ./config/jellyseerr:/app/config
    networks:
      - movieseer

networks:
  movieseer:
    external: true
