services:
  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - "${PROWLARR_PORT}:9696"
    volumes:
      - ./config/prowlarr:/config
    networks:
      - movieseer

networks:
  movieseer:
    external: true
