services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    network_mode: "service:gluetun"
    volumes:
      - ./config/qbittorrent:/config
      - ${DATA_PATH}:/data