services:
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - "${SABNZBD_PORT}:8080"
    volumes:
      - ./config/sabnzbd:/config
      - ${DATA_PATH}:/data
      - /Users/brendan/Downloads/sabnzbd-incomplete:/data/downloads/usenet/incomplete
    networks:
      - movieseer

networks:
  movieseer:
    external: true
