services:
  seerr:
    image: seerr/seerr
    container_name: seerr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - "${SEERR_PORT}:5055"
    volumes:
      - ./config/seerr:/app/config
    networks:
      - movieseer

networks:
  movieseer:
    external: true
